### * Obtener perfil por ID de usuario

GET http://localhost:3001/api/perfil/2


### * Crear un nuevo perfil
POST http://localhost:3000/api/perfil
Content-Type: application/json

{
  "nombre": "Nohora",
  "foto": "nora.jpg",
  "titulos": "Desarrolladora",
  "usuario_id": 1
}

### * Actualizar perfil por ID
PUT http://localhost:3000/api/perfil/1
Content-Type: application/json

{
  "nombre": "Nohora1",
  "foto": "nora1.jpg",
  "titulos": "Desarrolladora Senior"
}