### * Crear un proyectos
POST http://localhost:3001/api/proyecto
Content-Type: application/json

[
  {
    "titulo": "Proyecto de prueba 2",
    "descripcion": "Descripción del proyecto de prueba 2",
    "imagen": "http://ejemplo.com/imagen.jpg",
    "linkGithub": "http://github.com/usuario/proyecto",
    "linkDemo": "http://ejemplo.com/demo",
    "usuario_id": 1
  },
  {
    "titulo": "Otro proyecto de prueba 2",
    "descripcion": "Descripción de otro proyecto de prueba 2",
    "imagen": "http://ejemplo.com/otra-imagen.jpg",
    "linkGithub": "http://github.com/usuario/otro-proyecto",
    "linkDemo": "http://ejemplo.com/otra-demo",
    "usuario_id": 1
  }
]

### * Obtener todos los proyectos de un usuario
GET http://localhost:3001/api/proyecto/1

### * Modificar un proyectos
PUT http://localhost:3001/api/proyecto/1
Content-Type: application/json

[
  {
    "id": 3,
    "titulo": "Proyecto de prueba 3 modificado",
    "descripcion": "Descripción del proyecto de prueba 3",
    "imagen": "http://ejemplo.com/imagen.jpg",
    "linkGithub": "http://github.com/usuario/proyecto",
    "linkDemo": "http://ejemplo.com/demo",
    "tecnologias": [
      {
        "id": 2,
        "nombre_tecnologia": "typescript"
      }
    ]
  }
]

### * Eliminar un proyecto
DELETE http://localhost:3001/api/proyecto/11